version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "authorization-service"
s3_prefix = "authorization-service"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
image_repositories = []
